name: CM
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - libexpat=2.7.1
  - libffi=3.5.2
  - liblzma=5.8.1
  - libsqlite=3.51.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.6.0
  - pip=25.1.1
  - python=3.9.23
  - readline=8.2
  - setuptools=80.9.0
  - tk=8.6.13
  - tzdata=2025b
  - wheel=0.45.1
  - pip:
      - certifi==2025.10.5
      - h11==0.16.0
      - outcome==1.3.0.post0
      - pyjwt==2.10.1
      - pysocks==1.7.1
      - selenium==4.36.0
      - sortedcontainers==2.4.0
      - trio==0.31.0
      - trio-websocket==0.12.2
      - typing-extensions==4.15.0
      - urllib3==2.5.0
      - websocket-client==1.9.0
      - wsproto==1.2.0
